// Supabase Edge Function: thin wrapper that serves the platform-independent
// Hono API (apps/api). The bundle is generated by `pnpm build:edge`.
// Deploy: `supabase functions deploy api --no-verify-jwt` (the API verifies JWTs itself).
import { handler } from './_bundle/api.mjs';

Deno.serve(handler);
