// Bundles the API for Node (dist/server.mjs) or for Supabase Edge Functions /
// Deno (supabase/functions/api/_bundle/api.mjs).
import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const target = process.argv[2] ?? 'node';

if (target === 'edge') {
  const outfile = resolve(here, '../../supabase/functions/api/_bundle/api.mjs');
  await mkdir(dirname(outfile), { recursive: true });
  await build({
    entryPoints: [resolve(here, 'src/edge.ts')],
    outfile,
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    mainFields: ['module', 'main'],
    conditions: ['deno', 'worker', 'import'],
    external: ['node:*'],
    banner: { js: '// Generated by apps/api/build.mjs – do not edit.' },
    logLevel: 'info',
  });
} else {
  await build({
    entryPoints: [resolve(here, 'src/node.ts')],
    outfile: resolve(here, 'dist/server.mjs'),
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: 'node22',
    packages: 'external',
    logLevel: 'info',
  });
}
