// Bundles the API for Node (dist/server.mjs) or for Supabase Edge Functions /
// Deno (supabase/functions/api/_bundle/api.mjs).
import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { builtinModules } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
const target = process.argv[2] ?? 'node';

if (target === 'edge') {
  const outfile = resolve(here, '../../supabase/functions/api/_bundle/api.mjs');
  await mkdir(dirname(outfile), { recursive: true });
  await build({
    entryPoints: [resolve(here, 'src/edge.ts')],
    outfile,
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    mainFields: ['module', 'main'],
    conditions: ['deno', 'import'],
    // Deno supports Node built-ins through the node: scheme; rewrite bare imports.
    plugins: [
      {
        name: 'node-builtins',
        setup(b) {
          const builtins = new Set(builtinModules);
          b.onResolve({ filter: /.*/ }, (args) => {
            const name = args.path.replace(/^node:/, '');
            if (builtins.has(name) || builtins.has(name.split('/')[0]))
              return { path: `node:${name}`, external: true };
            return undefined;
          });
        },
      },
    ],
    banner: {
      js: [
        '// Generated by apps/api/build.mjs – do not edit.',
        "import { Buffer as __Buffer } from 'node:buffer';",
        "import __process from 'node:process';",
        'globalThis.Buffer ??= __Buffer;',
        'globalThis.process ??= __process;',
      ].join('\n'),
    },
    logLevel: 'info',
  });
} else {
  await build({
    entryPoints: [resolve(here, 'src/node.ts')],
    outfile: resolve(here, 'dist/server.mjs'),
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: 'node22',
    banner: {
      js: "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);",
    },
    logLevel: 'info',
  });
}
